### ISSUE TITLE
How about some contact?

### ISSUE THREAD

**Issue by ivellios** [butla/bultrowicz.com#1]
Hey ;) I tried to reach out to you, but cannot find any contact info, neither on the website nor in your presentations :) 

I'd like to ask if you like to come to 4Developers Festival in Warsaw in April. I create Python track and your talk may fit in perfectly :)

**Comment by butla** [comment]
Ok, I've added my e-mail (sort of), to my Github profile :) I think I'm interested, you can send me the details.
